/*
Implementation of the Voronoi Grid Generator. Actual implementation may use Fortune's Algorithm.
Currently, the Voronoi diagram is built by reading in the data file generated by the Delaunay
Grid Generator.


(c) 2015 Tony Liu.
*/

#include "VoronoiGridGenerator.h"

#include <string>

using namespace std;

VoronoiGridGenerator::VoronoiGridGenerator(string file){
	
}